

# About ABC http://wiki.c2.com/?AbcMetric
Metrics/AbcSize:
  Enabled: false

AllCops:
  rubocop:disable all
  
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*' # For CI broken


# pending status for avoiding the warning


